name: Fuzzing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initialize image name
      run: ./name.sh
    - name: Build the Docker image
      run: ./build.sh
    - name: Run the fuzz test
      run: ./run.sh
